import Head from 'next/head'
import Image from 'next/image'
import Main from '../components/main';
import Selectitems from './Selectitems'

export default function Home() {
  return (
    <div className='bg-gray-100'>
      <Head>
        <title>Naheed-Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        
          <Main/>
          
    </div>
  )
}
